import React, {
  createContext,
  useContext,
  useState,
  ReactNode,
  useEffect,
} from "react";

type Language = "en" | "hi" | "es" | "fr" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const defaultContext: LanguageContextType = {
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultContext);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.about": "About",
    "nav.howItWorks": "How It Works",
    "nav.checkIn": "Check In",
    "nav.mindfulness": "Mindfulness",
    "nav.sleep": "Sleep",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.chat": "Chat with HOPEr",
    "nav.getStarted": "Get Started",
    "nav.switchLanguage": "Switch Language",
    "nav.explore": "Explore",
    // Footer
    "footer.desc": "Supporting mental health awareness and providing resources for those in need.",
    "footer.quickLinks": "Quick Links",
    "footer.resources": "Resources",
    "footer.crisis": "Crisis Helpline",
    "footer.support": "Support Groups",
    "footer.blog": "Blog",
    // Features
    "features.title": "Explore Your Wellness",
    "features.subtitle": "Discover personalized tools designed to help you regain inner peace and manage stress effectively.",
    "features.assessmentDesc": "Take a personalized mental health assessment to understand your emotions.",
    "features.mindfulnessDesc": "Explore guided breathing, grounding exercises, and meditation.",
    "features.sleepDesc": "Prepare for a restful night with relaxation and sleep tracking tools.",
    // Meet Hoper
    "meet.titlePrefix": "Meet",
    "meet.subtitle": "A Safe, Empathetic AI Companion",
    "meet.desc": "HOPEr bridges the gap between student mental health needs and available support, providing immediate, safe, and therapeutically sound guidance whenever it's needed.",
    "meet.videoDesc": "Understanding the struggles students face and why we built an AI companion that truly cares",
    "meet.f1.title": "Safe & Verified",
    "meet.f1.desc": "Built on clinically verified mental health resources and spiritual wisdom with proper safety filters.",
    "meet.f2.title": "Empathetic Support",
    "meet.f2.desc": "Provides non-judgmental, compassionate conversations designed to reduce stress and build resilience.",
    "meet.f3.title": "24/7 Availability",
    "meet.f3.desc": "Always there when you need support, providing instant stress relief and motivational guidance.",
    "meet.f4.title": "Knowledge-Grounded",
    "meet.f4.desc": "All responses sourced from curated mental health texts, ensuring accuracy and therapeutic value.",
    "meet.f5.title": "Professional Referrals",
    "meet.f5.desc": "Recognizes when professional help is needed and guides users to appropriate mental health resources.",
    "meet.f6.title": "AI-Powered Insights",
    "meet.f6.desc": "Uses advanced AI to provide personalized mental health guidance tailored to your unique needs and situation.",
    // Objectives
    "obj.titlePrefix": "Our Core",
    "obj.titleSuffix": "Objectives",
    "obj.o1.title": "Provide Empathetic Guidance",
    "obj.o1.desc": "Reduce stress, motivate students, and foster resilience through compassionate conversations.",
    "obj.o2.title": "Minimize Hallucinations",
    "obj.o2.desc": "Grounded in verified knowledge to ensure responsible and beneficial interactions.",
    "obj.o3.title": "Develop Safe AI Companion",
    "obj.o3.desc": "Using RAG technology for accurate, reliable, and therapeutically sound responses.",
    "obj.o4.title": "Build Scalable Platform",
    "obj.o4.desc": "Designed for schools, universities, and communities to maximize positive impact.",
    "obj.o5.title": "Encourage Healthy Habits",
    "obj.o5.desc": "Promote well-being while preventing over-reliance on AI, fostering independence.",
    "obj.o6.title": "Ensure Privacy & Security",
    "obj.o6.desc": "Protect user data and maintain confidentiality while providing personalized support.",
    "obj.cta": "Experience HOPEr Today",
    // How It Works
    "hiw.titlePrefix": "How",
    "hiw.titleSuffix": "Works",
    "hiw.desc": "Our methodology combines cutting-edge AI technology with clinically verified mental health resources to deliver safe, empathetic, and effective support.",
    "hiw.s1.title": "Verified Knowledge Base",
    "hiw.s1.d1": "Clinically verified mental health resources and trusted spiritual wisdom form our foundation.",
    "hiw.s1.d2": "Curated from peer-reviewed research, therapeutic practices, and centuries of spiritual guidance.",
    "hiw.s2.title": "Semantic Retrieval",
    "hiw.s2.d1": "Pinecone vector database enables precise, context-aware information retrieval.",
    "hiw.s2.d2": "Advanced semantic search ensures the most relevant and helpful content for each query.",
    "hiw.s3.title": "AI Processing",
    "hiw.s3.d1": "Advanced AI architecture synthesizes verified information into empathetic responses.",
    "hiw.s3.d2": "Combines retrieval accuracy with generative empathy, minimizing harmful hallucinations.",
    "hiw.s4.title": "Safety Measures",
    "hiw.s4.d1": "Multiple layers of safety filters and clear disclaimers protect vulnerable users.",
    "hiw.s4.d2": "Built-in crisis detection, professional referral systems, and transparent limitations.",
    // AI Pipeline
    "pipe.titlePrefix": "Advanced AI",
    "pipe.titleSuffix": "Pipeline",
    "pipe.f1.title": "Retrieval-Augmented Generation (RAG)",
    "pipe.f1.desc": "Combines real-time information retrieval with generative AI for accurate, contextual responses.",
    "pipe.f2.title": "Vector Database Technology",
    "pipe.f2.desc": "Pinecone enables semantic understanding and precise retrieval of relevant mental health content.",
    "pipe.f3.title": "Safety-First Architecture",
    "pipe.f3.desc": "Multiple safety layers, content filtering, and crisis detection ensure user protection.",
    // CTA
    "cta.title": "Ready to Take the First Step?",
    "cta.desc": "Join thousands of others who have found hope, support, and healing through our community. Your journey to better mental health starts here.",
    "cta.btn": "Get Started Today",
    "cta.dialDesc": "Choose how you'd like to get in touch with us",
    "cta.email": "Email Us",
    "cta.call": "Call Us",
    "cta.visit": "Visit Us",
    // Mood Check
    "mood.badge": "New wellbeing tool",
    "mood.title": "Know Your Mood in Minutes",
    "mood.desc": "Answer eight gentle questions and get a friendly mood snapshot with supportive tips. This quick check-in can help you notice how you're doing today.",
    "mood.features": "Takes under 3 minutes · Safe · Non-judgmental · Mobile friendly",
    "mood.btnStart": "Start Mood Quiz",
    "mood.btnLearn": "Learn more",
    "mood.disclaimer": "Scores are indicators, not diagnoses. If you feel unsafe, please reach out to a trusted person or local helpline immediately.",
    // Assessment
    "assess.title": "HOPEr Check-In",
    "assess.prev": "Previous",
    "assess.q1": "How would you describe your mood right now?",
    "assess.q1.sub": "Pick the emoji that feels closest to how you feel.",
    "assess.q1.o1": "Very Low",
    "assess.q1.o2": "Low",
    "assess.q1.o3": "Okay",
    "assess.q1.o4": "Good",
    "assess.q1.o5": "Great",
    "assess.q2": "How has your sleep been lately?",
    "assess.q2.sub": "Think about the past 2–3 nights.",
    "assess.q2.o1": "Good — I'm well rested",
    "assess.q2.o2": "Okay — could be better",
    "assess.q2.o3": "Poor — trouble sleeping",
    "assess.q3": "Are you feeling anxious or overthinking?",
    "assess.q3.sub": "Be honest — this is just for you.",
    "assess.q3.o1": "Not at all",
    "assess.q3.o2": "A little bit",
    "assess.q3.o3": "Yes, quite a lot",
    "assess.q4": "How is your energy level right now?",
    "assess.q4.sub": "Physically and mentally.",
    "assess.q4.o1": "High — feeling active",
    "assess.q4.o2": "Medium — getting by",
    "assess.q4.o3": "Low — feeling drained",
    "assess.q5": "What do you feel you need most right now?",
    "assess.q5.sub": "There's no wrong answer.",
    "assess.q5.o1": "Talk it out",
    "assess.q5.o2": "Calm down",
    "assess.q5.o3": "Sleep better",
    "assess.q5.o4": "Just explore",
    "assess.btnNext": "Continue",
    "assess.btnResults": "See My Results",
    "assess.res.v1.title": "You seem to be doing well today",
    "assess.res.v1.desc": "That's wonderful! Even on good days, it's beautiful to take a moment and check in with yourself. HOPEr is here whenever you need a supportive space.",
    "assess.res.v2.title": "You seem a bit stressed today",
    "assess.res.v2.desc": "It's okay — life gets heavy sometimes. A few mindful moments can help reset your nervous system. Let HOPEr guide you gently.",
    "assess.res.v3.title": "You seem to be struggling a little",
    "assess.res.v3.desc": "You're not alone in this. Whether it's rest, breathing space, or just someone to talk to — HOPEr is here with no judgment.",
    "assess.res.v4.title": "You seem overwhelmed right now",
    "assess.res.v4.desc": "It takes courage to check in with yourself. Please know you're seen and valued. Let's take it one step at a time — HOPEr is right here with you.",
    "assess.msg.v1": "I can see you're doing well today! I'm here if you'd like to talk, explore something on your mind, or just have a mindful conversation.",
    "assess.msg.v2": "I understand you've been a bit anxious lately. Let's take it slow — I'm here to listen and support you. Would you like to share what's been on your mind?",
    "assess.msg.v3": "I see sleep has been tough lately. That can really affect everything else. I'm here to help — would you like to talk about what might be keeping you up?",
    "assess.msg.v4": "I can see you need some calm right now. I'm here with you. Would you like to try a quick breathing exercise together, or would you prefer to talk about what's going on?",
    "assess.msg.v5": "I can see things feel heavy right now. You don't have to face this alone — I'm here, and I'm listening. Take your time and share whatever feels right.",
    "assess.res.btnSleep": "Sleep Wellness Mode",
    "assess.res.btnMindfulness": "Mindfulness Mode",
    "assess.res.btnChat": "Talk to HOPEr",
    "assess.score.mood": "Mood",
    "assess.score.sleep": "Sleep",
    "assess.score.calm": "Calm",
    "assess.score.energy": "Energy",
    // Mindfulness
    "mind.title": "Mindfulness & Grounding",
    "mind.subtitle": "Choose a practice to center yourself. No pressure, no rush.",
    "mind.m1.title": "Breathing Exercise",
    "mind.m1.desc": "Calm your nervous system with guided breathwork.",
    "mind.m1.s1": "Inhale slowly through your nose",
    "mind.m1.s2": "Hold your breath",
    "mind.m1.s3": "Exhale slowly through your mouth",
    "mind.m2.title": "Grounding (5-4-3-2-1)",
    "mind.m2.desc": "Connect with your senses to reduce anxiety.",
    "mind.m2.s1": "5 things you can see",
    "mind.m2.s2": "4 things you can touch",
    "mind.m2.s3": "3 things you can hear",
    "mind.m2.s4": "2 things you can smell",
    "mind.m2.s5": "1 thing you can taste",
    "mind.m3.title": "Guided Reflection",
    "mind.m3.desc": "Short journaling prompts to process thoughts.",
    "mind.m3.s1": "What's one thing you're grateful for today?",
    "mind.m3.s2": "What's a small win you had recently?",
    "mind.m3.s3": "What would you like to let go of?",
    "mind.end": "End Session",
    "mind.breathingLoop": "Inhale... Hold... Exhale...",
    "mind.btnFinish": "Finish Session",
    "mind.btnNext": "Next Step",
    "mind.btnAssess": "Take a quick assessment first",
    // Sleep
    "sleep.title": "Sleep Wind-Down",
    "sleep.btnSkip": "Skip to End",
    "sleep.dayGreeting": "Good Afternoon",
    "sleep.nightGreeting": "Good Evening",
    "sleep.dayDesc": "It's never too early to plan for a better night's rest.",
    "sleep.nightDesc": "Let's prepare your mind and body for a restful sleep.",
    "sleep.dim.title": "Reduce screen brightness",
    "sleep.dim.desc": "Dim your screen or enable night shift to reduce blue light exposure.",
    "sleep.dim.i1": "Turn on Night Shift / Blue Light Filter",
    "sleep.dim.i2": "Lower screen brightness below 50%",
    "sleep.dim.i3": "Consider using an app like f.lux",
    "sleep.breath.title": "Breathing warm-up",
    "sleep.breath.desc": "A quick 4-7-8 breathing exercise to calm your nervous system.",
    "sleep.breath.note": "Repeat 4 cycles, breathing gently through your nose.",
    "sleep.script.title": "Calming sleep story",
    "sleep.script.desc": "Listen to a short guided relaxation script.",
    "sleep.script.content": "Imagine yourself lying in a comfortable meadow. The sky is a deep, velvety blue, dotted with stars. You feel the soft grass beneath you, and a gentle breeze brushes your skin. With each breath, you let go of the day's worries, sinking deeper into relaxation...",
    "sleep.script.note": "Continue reading at your own pace, or close your eyes and visualize.",
    "sleep.check.title": "Sleep hygiene checklist",
    "sleep.check.desc": "Personalized tips based on your assessment.",
    "sleep.check.i1": "Avoid news/social media 1 hour before bed",
    "sleep.check.i2": "Drink a cup of herbal tea (chamomile, lavender)",
    "sleep.check.i3": "Set your room temperature to 18–20°C",
    "sleep.check.i4": "Use blackout curtains or a sleep mask",
    "sleep.check.i5": "Keep a notepad by your bed for thoughts",
    "sleep.check.note": "Check off items as you complete them tonight.",
    "sleep.close.title": "You're all set",
    "sleep.close.desc": "Great job preparing for sleep. Sweet dreams!",
    "sleep.close.hero": "You've completed your wind‑down routine!",
    "sleep.close.sub": "Sleep well, and remember — HOPEr is here if you need support.",
    "sleep.hygiene.title": "Sleep Hygiene Tips",
    "sleep.hygiene.desc": "Daily habits for better sleep",
    "sleep.hygiene.i1": "Avoid caffeine after 2 PM",
    "sleep.hygiene.i2": "Keep your bedroom cool and dark",
    "sleep.hygiene.i3": "Stick to a consistent bedtime",
    "sleep.winddown.title": "Wind-Down Routine",
    "sleep.winddown.desc": "Evening relaxation ideas",
    "sleep.winddown.i1": "Read a book (no screens)",
    "sleep.winddown.i2": "Gentle stretching or yoga",
    "sleep.winddown.i3": "Write down tomorrow's tasks",
    "sleep.btnNext": "Continue",
    "sleep.btnPrevious": "Previous",
    "sleep.btnFinish": "Finish",
    "sleep.btnMindfulnessMode": "Try a guided meditation instead",
    "sleep.btnAskHoper": "Ask HOPEr about sleep",
    "sleep.btnAssess": "Take sleep assessment",
    "sleep.btnChat": "Chat with HOPEr",
    "sleep.chatQuery": "I just finished my sleep wind-down routine. Can we talk about sleep?",
    "sleep.footer": "Need more help with sleep?",
    // Hero
    "hero.title": "Your journey to inner peace ",
    "hero.titleHighlight": "starts with HOPEr",
    "hero.subtitle": "HOPEr is your AI-powered mental health companion, offering a safe space for reflection, grounding, and growth.",
    "hero.btnSupport": "24/7 Crisis Support",
    "hero.btnLearnMore": "Learn More",
    "hero.btnFeeling": "How are you feeling?",
    "hero.chatPlaceholder": "Ask me anything...",
    "hero.typewriter1": "How are you feeling today?",
    "hero.typewriter2": "I'm here to listen...",
    "hero.typewriter3": "What's on your mind?",
    // Features
    "features.title": "Explore Your Wellness",
    "features.subtitle": "Discover personalized tools designed to help you regain inner peace and manage stress effectively.",
    "features.assessmentDesc": "Take a personalized mental health assessment to understand your emotions.",
    "features.mindfulnessDesc": "Explore guided breathing, grounding exercises, and meditation.",
    "features.sleepDesc": "Prepare for a restful night with relaxation and sleep tracking tools.",
    // Common
    "common.home": "Home",
    "common.back": "Back",
    "common.next": "Next",
    "common.backHome": "Back to Home",
    "common.step": "Step",
    "common.of": "of",
    "common.more": "... and more",
    "common.finish": "Finish",
    "common.skip": "Skip",
    // Assessment
    "assessment.title": "How are you feeling right now?",
    // Mindfulness
    "mindfulness.title": "Mindfulness & Grounding",
    "mindfulness.subtitle":
      "Choose a practice to center yourself. No pressure, no rush.",
    // Sleep
    "sleep.title": "Sleep Wellness",
    "sleep.subtitle": "Wind down for a restful night.",
    "sleep.dayGreeting": "Planning for better sleep tonight?",
    "sleep.nightGreeting": "Ready to wind down?",
    "sleep.dayDesc": "Let's prepare for a restful night with some healthy habits.",
    "sleep.nightDesc": "Take a moment to relax and transition into sleep mode.",
    "sleep.btnFinish": "Finish",
    "sleep.btnNext": "Next Step",
    "sleep.btnPrevious": "Previous",
    "sleep.btnSkip": "Skip",
    // Chat
    "chat.placeholder": "Type your message here...",
    "chat.send": "Send",
    // Hero
    "hero.title": "Turning moments of stress into steps of hope ",
    "hero.titleHighlight": "Matters",
    "hero.subtitle": "A safe, empathetic AI companion providing 24/7 mental health support for students through clinically verified guidance and compassionate conversations.",
    "hero.btnSupport": "Get Support Now",
    "hero.btnLearnMore": "Learn More",
    "hero.btnFeeling": "How are you feeling?",
    "hero.chatPlaceholder": "e.g. I'm feeling overwhelmed with exams...",
    "hero.typewriter1": "What's on your mind?",
    "hero.typewriter2": "How are you feeling today?",
    "hero.typewriter3": "Is there something you'd like to share?",
  },
  hi: {
    "nav.about": "हमारे बारे में",
    "nav.howItWorks": "कैसे काम करता है",
    "nav.checkIn": "चेक इन",
    "nav.mindfulness": "माइंडफुलनेस",
    "nav.sleep": "नींद",
    "nav.faq": "सवाल-जवाब",
    "nav.contact": "संपर्क",
    "nav.chat": "HOPEr से बात करें",
    "nav.getStarted": "शुरू करें",
    "nav.switchLanguage": "भाषा बदलें",
    "nav.explore": "खोजें",
    // Footer
    "footer.desc": "मानसिक स्वास्थ्य जागरूकता का समर्थन और जरूरतमंदों के लिए संसाधन प्रदान करना।",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.resources": "संसाधन",
    "footer.crisis": "क्राइसिस हेल्पलाइन",
    "footer.support": "सहायता समूह",
    "footer.blog": "ब्लॉग",
    // Features
    "features.title": "अपने स्वास्थ्य का अन्वेषण करें",
    "features.subtitle": "आंतरिक शांति प्राप्त करने और तनाव को प्रभावी ढंग से प्रबंधित करने में आपकी सहायता के लिए डिज़ाइन किए गए व्यक्तिगत उपकरण खोजें।",
    "features.assessmentDesc": "अपनी भावनाओं को समझने के लिए एक व्यक्तिगत मानसिक स्वास्थ्य मूल्यांकन लें।",
    "features.mindfulnessDesc": "निर्देशित श्वास, ग्राउंडिंग अभ्यास और ध्यान का अन्वेषण करें।",
    "features.sleepDesc": "विश्राम और नींद ट्रैकिंग टूल के साथ एक आरामदायक रात की तैयारी करें।",
    // Meet Hoper
    "meet.titlePrefix": "मिलें",
    "meet.subtitle": "एक सुरक्षित और सहानुभूतिशील AI साथी",
    "meet.desc": "HOPEr छात्र मानसिक स्वास्थ्य आवश्यकताओं और उपलब्ध सहायता के बीच की खाई को पाटता है, जो तत्काल, सुरक्षित और चिकित्सकीय रूप से ध्वनि मार्गदर्शन प्रदान करता है।",
    "meet.videoDesc": "छात्रों के संघर्षों को समझना और यह कि हमने वास्तव में परवाह करने वाले AI साथी का निर्माण क्यों किया",
    "meet.f1.title": "सुरक्षित और सत्यापित",
    "meet.f1.desc": "उचित सुरक्षा फ़िल्टर के साथ चिकित्सकीय रूप से सत्यापित संसाधनों और आध्यात्मिक ज्ञान पर निर्मित।",
    "meet.f2.title": "सहानुभूतिपूर्ण समर्थन",
    "meet.f2.desc": "तनाव को कम करने और लचीलापन बनाने के लिए गैर-निर्णयात्मक, दयालु बातचीत प्रदान करता है।",
    "meet.f3.title": "24/7 उपलब्ध",
    "meet.f3.desc": "जब भी आपको सहायता की आवश्यकता हो, हमेशा मौजूद रहता है।",
    "meet.f4.title": "ज्ञान-आधारित",
    "meet.f4.desc": "सभी प्रतिक्रियाएँ क्यूरेटेड मानसिक स्वास्थ्य ग्रंथों से प्राप्त होती हैं।",
    "meet.f5.title": "पेशेवर रेफरल",
    "meet.f5.desc": "जब पेशेवर मदद की आवश्यकता होती है तो पहचानता है और मार्गदर्शन करता है।",
    "meet.f6.title": "AI-संचालित अंतर्दृष्टि",
    "meet.f6.desc": "आपकी विशिष्ट आवश्यकताओं के अनुरूप व्यक्तिगत मानसिक स्वास्थ्य मार्गदर्शन।",
    // Objectives
    "obj.titlePrefix": "हमारे मुख्य",
    "obj.titleSuffix": "उद्देश्य",
    "obj.o1.title": "सहानुभूतिपूर्ण मार्गदर्शन प्रदान करें",
    "obj.o1.desc": "करुणापूर्ण बातचीत के माध्यम से तनाव कम करें, छात्रों को प्रेरित करें और लचीलापन बढ़ाएं।",
    "obj.o2.title": "भ्रम को कम करें",
    "obj.o2.desc": "जिम्मेदार और लाभकारी अंतःक्रियाओं को सुनिश्चित करने के लिए सत्यापित ज्ञान पर आधारित।",
    "obj.o3.title": "सुरक्षित AI साथी विकसित करें",
    "obj.o3.desc": "सटीक, विश्वसनीय और चिकित्सकीय रूप से ध्वनि प्रतिक्रियाओं के लिए RAG तकनीक का उपयोग करना।",
    "obj.o4.title": "स्केलेबल प्लेटफॉर्म बनाएं",
    "obj.o4.desc": "सकारात्मक प्रभाव को अधिकतम करने के लिए स्कूलों और समुदायों के लिए डिज़ाइन किया गया।",
    "obj.o5.title": "स्वस्थ आदतों को प्रोत्साहित करें",
    "obj.o5.desc": "AI पर अति-निर्भरता को रोकते हुए कल्याण को बढ़ावा देना।",
    "obj.o6.title": "गोपनीयता और सुरक्षा सुनिश्चित करें",
    "obj.o6.desc": "उपयोगकर्ता डेटा को सुरक्षित रखें और व्यक्तिगत सहायता प्रदान करते हुए गोपनीयता बनाए रखें।",
    "obj.cta": "आज HOPEr का अनुभव करें",
    // How It Works
    "hiw.titlePrefix": "कैसे",
    "hiw.titleSuffix": "काम करता है",
    "hiw.desc": "हमारी पद्धति सुरक्षित समर्थन प्रदान करने के लिए अत्याधुनिक एआई तकनीक को जोड़ती है।",
    "hiw.s1.title": "सत्यापित ज्ञानकोष",
    "hiw.s1.d1": "चिकित्सकीय रूप से सत्यापित मानसिक स्वास्थ्य संसाधन।",
    "hiw.s1.d2": "सहकर्मी-समीक्षित शोध से क्यूरेट किया गया।",
    "hiw.s2.title": "अर्थ संबंधी पुनर्प्राप्ति",
    "hiw.s2.d1": "पाइनकोन वेक्टर डेटाबेस सटीक पुनर्प्राप्ति को सक्षम करता है।",
    "hiw.s2.d2": "कस्टम खोज प्रत्येक क्वेरी के लिए सबसे प्रासंगिक सामग्री सुनिश्चित करती है।",
    "hiw.s3.title": "AI प्रसंस्करण",
    "hiw.s3.d1": "उन्नत AI वास्तुकला सत्यापित जानकारी को संश्लेषित करती है।",
    "hiw.s3.d2": "पुनर्प्राप्ति सटीकता को जोड़ती है।",
    "hiw.s4.title": "सुरक्षा उपाय",
    "hiw.s4.d1": "सुरक्षा फिल्टर की कई परतें।",
    "hiw.s4.d2": "अंतर्निहित संकट का पता लगाना।",
    // AI Pipeline
    "pipe.titlePrefix": "उन्नत AI",
    "pipe.titleSuffix": "पाइपलाइन",
    "pipe.f1.title": "पुनर्प्राप्ति-संवर्धित उत्पादन (RAG)",
    "pipe.f1.desc": "सटीक प्रतिक्रियाओं के लिए जनरेटिव AI के साथ रीयल-टाइम सूचना को जोड़ती है।",
    "pipe.f2.title": "वेक्टर डेटाबेस तकनीक",
    "pipe.f2.desc": "पाइनकोन अर्थ संबंधी समझ को सक्षम करता है।",
    "pipe.f3.title": "सुरक्षा-प्रथम वास्तुकला",
    "pipe.f3.desc": "एकाधिक सुरक्षा परतें उपयोगकर्ता सुरक्षा सुनिश्चित करती हैं।",
    // CTA
    "cta.title": "पहला कदम उठाने के लिए तैयार हैं?",
    "cta.desc": "उन हजारों अन्य लोगों से जुड़ें जिन्होंने हमारे समुदाय के माध्यम से आशा, समर्थन और उपचार पाया है।",
    "cta.btn": "आज ही शुरू करें",
    "cta.dialDesc": "चुनें कि आप हमसे कैसे संपर्क करना चाहेंगे",
    "cta.email": "हमें ईमेल करें",
    "cta.call": "हमें कॉल करें",
    "cta.visit": "हमसे मिलें",
    // Mood Check
    "mood.badge": "नया कल्याण टूल",
    "mood.title": "मिनटों में अपना मूड जानें",
    "mood.desc": "आठ सौम्य प्रश्नों का उत्तर दें और सहायक युक्तियों के साथ एक अनुकूल मूड स्नैपशॉट प्राप्त करें।",
    "mood.features": "3 मिनट से कम समय लगता है · सुरक्षित · गैर-निर्णयात्मक · मोबाइल के अनुकूल",
    "mood.btnStart": "मूड क्विज़ शुरू करें",
    "mood.btnLearn": "और जानें",
    "mood.disclaimer": "स्कोर संकेतक हैं, निदान नहीं। यदि आप असुरक्षित महसूस करते हैं, तो कृपया तुरंत सहायता लें।",
    // Assessment
    "assess.title": "HOPEr चेक-इन",
    "assess.prev": "पीछे",
    "assess.q1": "आप अभी अपने मूड का वर्णन कैसे करेंगे?",
    "assess.q1.sub": "वह इमोजी चुनें जो आपके महसूस करने के सबसे करीब हो।",
    "assess.q1.o1": "बहुत कम",
    "assess.q1.o2": "कम",
    "assess.q1.o3": "ठीक है",
    "assess.q1.o4": "अच्छा",
    "assess.q1.o5": "बहुत बढ़िया",
    "assess.q2": "हाल ही में आपकी नींद कैसी रही है?",
    "assess.q2.sub": "पिछले 2-3 रातों के बारे में सोचें।",
    "assess.q2.o1": "अच्छा - मैं पूरी तरह से आराम कर रहा हूँ",
    "assess.q2.o2": "ठीक है - बेहतर हो सकता था",
    "assess.q2.o3": "खराब - सोने में परेशानी",
    "assess.q3": "क्या आप चिंतित महसूस कर रहे हैं या बहुत अधिक सोच रहे हैं?",
    "assess.q3.sub": "ईमानदार रहें - यह केवल आपके लिए है।",
    "assess.q3.o1": "बिल्कुल नहीं",
    "assess.q3.o2": "थोड़ा बहुत",
    "assess.q3.o3": "हाँ, काफी ज्यादा",
    "assess.q4": "अभी आपका ऊर्जा स्तर कैसा है?",
    "assess.q4.sub": "शारीरिक और मानसिक रूप से।",
    "assess.q4.o1": "उच्च - सक्रिय महसूस कर रहा हूँ",
    "assess.q4.o2": "मध्यम - बस चल रहा हूँ",
    "assess.q4.o3": "कम - थकान महसूस कर रहा हूँ",
    "assess.q5": "आपको क्या लगता है कि अभी आपको सबसे ज्यादा क्या चाहिए?",
    "assess.q5.sub": "कोई गलत उत्तर नहीं है।",
    "assess.q5.o1": "बात करना",
    "assess.q5.o2": "शांत होना",
    "assess.q5.o3": "बेहतर नींद",
    "assess.q5.o4": "बस एक्सप्लोर करना",
    "assess.btnNext": "जारी रखें",
    "assess.btnResults": "मेरे परिणाम देखें",
    "assess.res.v1.title": "आप आज अच्छे लग रहे हैं",
    "assess.res.v1.desc": "यह बहुत अच्छा है! अच्छे दिनों में भी, एक पल लेना और अपने आप से चेक-इन करना सुंदर है।",
    "assess.res.v2.title": "आप आज थोड़े तनावग्रस्त लग रहे हैं",
    "assess.res.v2.desc": "ठीक है - जीवन कभी-कभी भारी हो जाता है। कुछ सचेत पल मदद कर सकते हैं।",
    "assess.res.v3.title": "आप थोड़ा संघर्ष कर रहे हैं",
    "assess.res.v3.desc": "आप इसमें अकेले नहीं हैं। चाहे वह आराम हो, सांस लेने की जगह हो, या सिर्फ बात करने के लिए कोई - HOPEr यहाँ है।",
    "assess.res.v4.title": "आप अभी अभिभूत लग रहे हैं",
    "assess.res.v4.desc": "अपने आप से चेक-इन करने के लिए साहस चाहिए। कृपया जानें कि आप देखे और मूल्यवान हैं।",
    "assess.msg.v1": "मैं देख सकता हूँ कि आप आज अच्छा कर रहे हैं! मैं यहाँ हूँ अगर आप बात करना चाहते हैं।",
    "assess.msg.v2": "मैं समझता हूँ कि आप हाल ही में थोड़े चिंतित रहे हैं। चलिए धीरे-धीरे चलते हैं - मैं सुनने और समर्थन करने के लिए यहाँ हूँ।",
    "assess.msg.v3": "मैं देख रहा हूँ कि हाल ही में नींद मुश्किल रही है। वह सब कुछ प्रभावित कर सकती है।",
    "assess.msg.v4": "मैं देख सकता हूँ कि आपको अभी कुछ शांति की आवश्यकता है। मैं आपके साथ हूँ।",
    "assess.msg.v5": "मैं देख सकता हूँ कि चीजें अभी भारी लग रही हैं। आपको अकेले इसका सामना नहीं करना है।",
    "assess.res.btnSleep": "नींद कल्याण मोड",
    "assess.res.btnMindfulness": "माइंडफुलनेस मोड",
    "assess.res.btnChat": "HOPEr से बात करें",
    "score.mood": "मूड",
    "score.sleep": "नींद",
    "score.calm": "शांति",
    "score.energy": "ऊर्जा",
    // Mindfulness
    "mind.title": "माइंडफुलनेस और ग्राउंडिंग",
    "mind.subtitle": "अपने आप को केंद्रित करने के लिए अभ्यास चुनें। कोई दबाव नहीं, कोई जल्दी नहीं।",
    "mind.m1.title": "सांस लेने का व्यायाम",
    "mind.m1.desc": "गाइडेड ब्रीदवर्क के साथ अपने तंत्रिका तंत्र को शांत करें।",
    "mind.m1.s1": "अपनी नाक से धीरे-धीरे सांस लें",
    "mind.m1.s2": "अपनी सांस रोकें",
    "mind.m1.s3": "अपने मुंह से धीरे-धीरे सांस छोड़ें",
    "mind.m2.title": "ग्राउंडिंग (5-4-3-2-1)",
    "mind.m2.desc": "चिंता को कम करने के लिए अपनी इंद्रियों से जुड़ें।",
    "mind.m2.s1": "5 चीजें जो आप देख सकते हैं",
    "mind.m2.s2": "4 चीजें जिन्हें आप छू सकते हैं",
    "mind.m2.s3": "3 चीजें जो आप सुन सकते हैं",
    "mind.m2.s4": "2 चीजें जिन्हें आप सूंघ सकते हैं",
    "mind.m2.s5": "1 चीज जिसका आप स्वाद ले सकते हैं",
    "mind.m3.title": "निर्देशित प्रतिबिंब",
    "mind.m3.desc": "विचारों को संसाधित करने के लिए छोटे जर्नलिंग संकेत।",
    "mind.m3.s1": "आज आप किस एक चीज के लिए आभारी हैं?",
    "mind.m3.s2": "आपकी हाल ही में हुई एक छोटी सी जीत क्या है?",
    "mind.m3.s3": "आप क्या छोड़ना चाहेंगे?",
    "mind.end": "सत्र समाप्त करें",
    "mind.breathingLoop": "सांस लें... रोकें... सांस छोड़ें...",
    "mind.btnFinish": "सत्र समाप्त करें",
    "mind.btnNext": "अगला कदम",
    "mind.btnAssess": "पहले एक त्वरित मूल्यांकन करें",
    // Sleep
    "sleep.title": "नींद की तैयारी",
    "sleep.btnSkip": "छोड़ें",
    "sleep.dayGreeting": "शुभ दोपहर",
    "sleep.nightGreeting": "शुभ संध्या",
    "sleep.dayDesc": "बेहतर रात के आराम के लिए योजना बनाना कभी भी जल्दी नहीं है।",
    "sleep.nightDesc": "आइए आपके मन और शरीर को आरामदायक नींद के लिए तैयार करें।",
    "sleep.dim.title": "स्क्रीन की चमक कम करें",
    "sleep.dim.desc": "नीली रोशनी के संपर्क को कम करने के लिए अपनी स्क्रीन को धुंधला करें।",
    "sleep.dim.i1": "नाइट शिफ्ट / ब्लू लाइट फिल्टर चालू करें",
    "sleep.dim.i2": "स्क्रीन की चमक 50% से कम करें",
    "sleep.dim.i3": "f.lux जैसे ऐप का उपयोग करने पर विचार करें",
    "sleep.breath.title": "सांस लेने का वार्म-अप",
    "sleep.breath.desc": "आपके तंत्रिका तंत्र को शांत करने के लिए एक त्वरित 4-7-8 सांस लेने का व्यायाम।",
    "sleep.breath.note": "अपनी नाक से धीरे-धीरे सांस लेते हुए 4 चक्र दोहराएं।",
    "sleep.script.title": "शांत नींद की कहानी",
    "sleep.script.desc": "एक संक्षिप्त निर्देशित विश्राम लिपि सुनें।",
    "sleep.script.content": "कल्पना कीजिए कि आप एक आरामदायक घास के मैदान में लेटे हैं। आकाश गहरा, मखमली नीला है, सितारों से भरा हुआ। आप अपने नीचे नरम घास को महसूस करते हैं, और एक हल्की हवा आपकी त्वचा को छूती है। प्रत्येक सांस के साथ, आप दिन की चिंताओं को छोड़ देते हैं, विश्राम में गहराई से डूब जाते हैं...",
    "sleep.script.note": "अपनी गति से पढ़ना जारी रखें, या अपनी आँखें बंद करें और कल्पना करें।",
    "sleep.check.title": "नींद स्वच्छता चेकलिस्ट",
    "sleep.check.desc": "आपके मूल्यांकन के आधार पर व्यक्तिगत सुझाव।",
    "sleep.check.i1": "सोने से 1 घंटा पहले समाचार/सोशल मीडिया से बचें",
    "sleep.check.i2": "हर्बल चाय का एक कप पिएं (कैमोमाइल, लैवेंडर)",
    "sleep.check.i3": "अपने कमरे का तापमान 18-20 डिग्री सेल्सियस सेट करें",
    "sleep.check.i4": "ब्लैकआउट पर्दों या स्लीप मास्क का उपयोग करें",
    "sleep.check.i5": "विचारों के लिए अपने बिस्तर के पास एक नोटपैड रखें",
    "sleep.check.note": "जैसे ही आप उन्हें आज रात पूरा करते हैं, वस्तुओं को चेक ऑफ करें।",
    "sleep.close.title": "सब तैयार है",
    "sleep.close.desc": "नींद की तैयारी के लिए बढ़िया काम। शुभ रात्रि!",
    "sleep.close.hero": "आपने अपनी विंड-डाउन रूटीन पूरी कर ली है!",
    "sleep.close.sub": "अच्छी नींद लें, और याद रखें - यदि आपको सहायता की आवश्यकता है तो HOPEr यहाँ है।",
    "sleep.hygiene.title": "नींद स्वच्छता सुझाव",
    "sleep.hygiene.desc": "बेहतर नींद के लिए दैनिक आदतें",
    "sleep.hygiene.i1": "दोपहर 2 बजे के बाद कैफीन से बचें",
    "sleep.hygiene.i2": "अपने बेडरूम को ठंडा और अंधेरा रखें",
    "sleep.hygiene.i3": "सोने के लिए एक सुसंगत समय पर टिके रहें",
    "sleep.winddown.title": "विंड-डाउन रूटीन",
    "sleep.winddown.desc": "शाम के विश्राम के विचार",
    "sleep.winddown.i1": "किताब पढ़ें (कोई स्क्रीन नहीं)",
    "sleep.winddown.i2": "हल्का स्ट्रेचिंग या योग",
    "sleep.winddown.i3": "कल के कार्यों को लिख लें",
    "sleep.btnNext": "जारी रखें",
    "sleep.btnPrevious": "पीछे",
    "sleep.btnFinish": "समाप्त",
    "sleep.btnMindfulnessMode": "इसके बजाय एक निर्देशित ध्यान का प्रयास करें",
    "sleep.btnAskHoper": "नींद के बारे में HOPEr से पूछें",
    "sleep.btnAssess": "नींद का मूल्यांकन करें",
    "sleep.btnChat": "HOPEr से चैट करें",
    "sleep.chatQuery": "मैंने अभी-अभी अपनी नींद की विंड-डाउन रूटीन पूरी की है। क्या हम नींद के बारे में बात कर सकते हैं?",
    "sleep.footer": "नींद के बारे with और मदद चाहिए?",
    // Hero
    "hero.title": "आपकी आंतरिक शांति की यात्रा ",
    "hero.titleHighlight": "HOPEr के साथ शुरू होती है",
    "hero.subtitle": "HOPEr आपका AI-संचालित मानसिक स्वास्थ्य साथी है, जो प्रतिबिंब, ग्राउंडिंग और विकास के लिए एक सुरक्षित स्थान प्रदान करता है।",
    "hero.btnSupport": "24/7 संकट सहायता",
    "hero.btnLearnMore": "और जानें",
    "hero.btnFeeling": "आप कैसा महसूस कर रहे हैं?",
    "hero.chatPlaceholder": "मुझसे कुछ भी पूछें...",
    "hero.typewriter1": "आज आप कैसा महसूस कर रहे हैं?",
    "hero.typewriter2": "मैं सुनने के लिए यहाँ हूँ...",
    "hero.typewriter3": "आपके मन में क्या है?",
    // Features
    "features.title": "अपने कल्याण का अन्वेषण करें",
    "features.subtitle": "अपनी भावनाओं को समझने के लिए व्यक्तिगत मानसिक स्वास्थ्य मूल्यांकन लें।",
    "features.assessmentDesc": "अपनी भावनाओं को समझने के लिए व्यक्तिगत मानसिक स्वास्थ्य मूल्यांकन लें।",
    "features.mindfulnessDesc": "निर्देशित श्वास, ग्राउंडिंग अभ्यास और ध्यान का अन्वेषण करें।",
    "features.sleepDesc": "विश्राम और नींद ट्रैकिंग टूल के साथ एक आरामदायक रात के लिए तैयार हों।",
    // Common
    "common.home": "होम",
    "common.back": "पीछे",
    "common.next": "आगे",
    "common.backHome": "होम पर वापस",
    "common.step": "कदम",
    "common.of": "का",
    "common.more": "... और अधिक",
    "common.finish": "समाप्त",
    "common.skip": "छोड़ें",
    "assessment.title": "आप अभी कैसा महसूस कर रहे हैं?",
    "mindfulness.title": "माइंडफुलनेस और ग्राउंडिंग",
    "mindfulness.subtitle":
      "खुद को केंद्रित करने के लिए एक अभ्यास चुनें। कोई दबाव नहीं, कोई जल्दी नहीं।",
    "sleep.title": "नींद स्वास्थ्य",
    "sleep.subtitle": "आरामदायक रात के लिए तैयार हों।",
    "sleep.dayGreeting": "आज रात बेहतर नींद की योजना बना रहे हैं?",
    "sleep.nightGreeting": "क्या आप आराम करने के लिए तैयार हैं?",
    "sleep.dayDesc": "आइए कुछ स्वस्थ आदतों के साथ एक आरामदायक रात की तैयारी करें।",
    "sleep.nightDesc": "आराम करने और स्लीप मोड में जाने के लिए कुछ समय निकालें।",
    "sleep.btnFinish": "समाप्त करें",
    "sleep.btnNext": "अगला कदम",
    "sleep.btnPrevious": "पिछला",
    "sleep.btnSkip": "छोड़ें",
    "chat.placeholder": "यहाँ अपना संदेश लिखें...",
    "chat.send": "भेजें",
    "hero.title": "तनाव के पलों को उम्मीद के कदमों में बदलना ",
    "hero.titleHighlight": "महत्वपूर्ण है",
    "hero.subtitle": "छात्रों के लिए 24/7 मानसिक स्वास्थ्य सहायता प्रदान करने वाला एक सुरक्षित और सहानुभूतिपूर्ण AI साथी, जो क्लीनिकली प्रमाणित मार्गदर्शन और बातचीत के माध्यम से मदद करता है।",
    "hero.btnSupport": "अभी सहायता प्राप्त करें",
    "hero.btnLearnMore": "अधिक जानें",
    "hero.btnFeeling": "आप कैसा महसूस कर रहे हैं?",
    "hero.chatPlaceholder": "उदा. मुझे परीक्षाओं को लेकर घबराहट हो रही है...",
    "hero.typewriter1": "आपके मन में क्या है?",
    "hero.typewriter2": "आज आप कैसा महसूस कर रहे हैं?",
    "hero.typewriter3": "क्या आप कुछ साझा करना चाहेंगे?",
  },
  es: {
    "nav.about": "Acerca de",
    "nav.howItWorks": "Cómo funciona",
    "nav.checkIn": "Registrarse",
    "nav.mindfulness": "Atención plena",
    "nav.sleep": "Sueño",
    "nav.faq": "Preguntas frecuentes",
    "nav.contact": "Contacto",
    "nav.chat": "Chatea con HOPEr",
    "nav.getStarted": "Empezar",
    "nav.switchLanguage": "Cambiar idioma",
    "nav.explore": "Explorar",
    // Footer
    "footer.desc": "Apoyando la conciencia sobre la salud mental y proporcionando recursos para quienes lo necesitan.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.resources": "Recursos",
    "footer.crisis": "Línea de Crisis",
    "footer.support": "Grupos de Apoyo",
    "footer.blog": "Blog",
    // Features
    "features.title": "Explora tu bienestar",
    "features.subtitle": "Descubre herramientas personalizadas diseñadas para ayudarte a recuperar la paz interior y manejar el estrés de manera efectiva.",
    "features.assessmentDesc": "Realiza una evaluación de salud mental personalizada para comprender tus emociones.",
    "features.mindfulnessDesc": "Explora la respiración guiada, los ejercicios de enraizamiento y la meditación.",
    "features.sleepDesc": "Prepárate para una noche de descanso con herramientas de relajación y seguimiento del sueño.",
    // Meet Hoper
    "meet.titlePrefix": "Conoce a",
    "meet.subtitle": "Un compañero de IA seguro y empático",
    "meet.desc": "HOPEr cierra la brecha entre las necesidades de salud mental de los estudiantes y el apoyo disponible, brindando orientación inmediata, segura y terapéuticamente sólida siempre que sea necesario.",
    "meet.videoDesc": "Comprender las luchas que enfrentan los estudiantes y por qué creamos un compañero de IA que realmente se preocupa",
    "meet.f1.title": "Seguro y verificado",
    "meet.f1.desc": "Construido sobre recursos de salud mental verificados clínicamente y sabiduría espiritual con filtros de seguridad adecuados.",
    "meet.f2.title": "Apoyo empático",
    "meet.f2.desc": "Proporciona conversaciones compasivas y sin prejuicios diseñadas para reducir el estrés y desarrollar la resiliencia.",
    "meet.f3.title": "Disponibilidad 24/7",
    "meet.f3.desc": "Siempre allí cuando necesita apoyo, brindando alivio instantáneo del estrés.",
    "meet.f4.title": "Basado en el conocimiento",
    "meet.f4.desc": "Todas las respuestas provienen de textos de salud mental curados, asegurando precisión.",
    "meet.f5.title": "Referencias profesionales",
    "meet.f5.desc": "Reconoce cuándo se necesita ayuda profesional y guía a los usuarios hacia recursos de salud mental apropiados.",
    "meet.f6.title": "Información impulsada por IA",
    "meet.f6.desc": "Utiliza IA avanzada para brindar orientación de salud mental personalizada.",
    // Objectives
    "obj.titlePrefix": "Nuestros principales",
    "obj.titleSuffix": "Objetivos",
    "obj.o1.title": "Proporcionar orientación empática",
    "obj.o1.desc": "Reduzca el estrés, motive a los estudiantes y fomente la resiliencia.",
    "obj.o2.title": "Minimizar alucinaciones",
    "obj.o2.desc": "Basado en conocimiento verificado para asegurar interacciones responsables.",
    "obj.o3.title": "Desarrollar compañero de IA seguro",
    "obj.o3.desc": "Uso de tecnología RAG para respuestas precisas y confiables.",
    "obj.o4.title": "Construir plataforma escalable",
    "obj.o4.desc": "Diseñado para escuelas, universidades y comunidades.",
    "obj.o5.title": "Fomentar hábitos saludables",
    "obj.o5.desc": "Promover el bienestar al tiempo que se previene la dependencia excesiva de la IA.",
    "obj.o6.title": "Garantizar la privacidad",
    "obj.o6.desc": "Proteger los datos del usuario y mantener la confidencialidad.",
    "obj.cta": "Experimente HOPEr Hoy",
    // How It Works
    "hiw.titlePrefix": "Cómo funciona",
    "hiw.titleSuffix": "",
    "hiw.desc": "Nuestra metodología combina tecnología de inteligencia artificial de vanguardia con recursos verificados.",
    "hiw.s1.title": "Base de conocimientos verificada",
    "hiw.s1.d1": "Recursos de salud mental clínicamente verificados.",
    "hiw.s1.d2": "Seleccionado de investigaciones revisadas por pares.",
    "hiw.s2.title": "Recuperación semántica",
    "hiw.s2.d1": "La base de datos vectorial Pinecone permite una recuperación precisa.",
    "hiw.s2.d2": "La búsqueda semántica avanzada garantiza contenido relevante.",
    "hiw.s3.title": "Procesamiento de IA",
    "hiw.s3.d1": "La arquitectura avanzada de IA sintetiza información verificada.",
    "hiw.s3.d2": "Combina la precisión de recuperación con empatía generativa.",
    "hiw.s4.title": "Medidas de seguridad",
    "hiw.s4.d1": "Múltiples capas de filtros de seguridad.",
    "hiw.s4.d2": "Detección de crisis incorporada.",
    // AI Pipeline
    "pipe.titlePrefix": "Tubería de",
    "pipe.titleSuffix": "IA Avanzada",
    "pipe.f1.title": "Generación Aumentada por Recuperación (RAG)",
    "pipe.f1.desc": "Combina la recuperación de información en tiempo real con IA generativa.",
    "pipe.f2.title": "Tecnología de base de datos vectorial",
    "pipe.f2.desc": "Pinecone permite la comprensión semántica.",
    "pipe.f3.title": "Arquitectura de seguridad",
    "pipe.f3.desc": "Las múltiples capas de seguridad garantizan la protección del usuario.",
    // CTA
    "cta.title": "¿Listo para dar el primer paso?",
    "cta.desc": "Únete a miles de personas que han encontrado esperanza y apoyo en nuestra comunidad.",
    "cta.btn": "Comienza hoy",
    "cta.dialDesc": "Elige cómo quieres ponerte en contacto con nosotros",
    "cta.email": "Envíanos un correo",
    "cta.call": "Llámanos",
    "cta.visit": "Visítanos",
    // Mood Check
    "mood.badge": "Nueva herramienta de bienestar",
    "mood.title": "Conoce tu estado de ánimo en minutos",
    "mood.desc": "Responde ocho preguntas y obtén un resumen de tu estado de ánimo con consejos de apoyo.",
    "mood.features": "Toma menos de 3 minutos · Seguro · Sin prejuicios · Apto para móviles",
    "mood.btnStart": "Comenzar el cuestionario",
    "mood.btnLearn": "Saber más",
    "mood.disclaimer": "Las puntuaciones son indicadores, no diagnósticos. Si te sientes inseguro, busca asistencia.",
    // Assessment
    "assess.title": "HOPEr Registro",
    "assess.prev": "Anterior",
    "assess.q1": "¿Cómo describirías tu estado de ánimo en este momento?",
    "assess.q1.sub": "Elige el emoji que mejor represente cómo te sientes.",
    "assess.q1.o1": "Muy bajo",
    "assess.q1.o2": "Bajo",
    "assess.q1.o3": "Bien",
    "assess.q1.o4": "Bueno",
    "assess.q1.o5": "Genial",
    "assess.q2": "¿Cómo ha sido tu sueño últimamente?",
    "assess.q2.sub": "Piensa en las últimas 2-3 noches.",
    "assess.q2.o1": "Bueno - He descansado bien",
    "assess.q2.o2": "Bien - podría ser mejor",
    "assess.q2.o3": "Malo - problemas para dormir",
    "assess.q3": "¿Te sientes ansioso o pensando demasiado?",
    "assess.q3.sub": "Sé sincero - esto es solo para ti.",
    "assess.q3.o1": "Para nada",
    "assess.q3.o2": "Un poquito",
    "assess.q3.o3": "Sí, bastante",
    "assess.q4": "¿Cómo está tu nivel de energía ahora?",
    "assess.q4.sub": "Física y mentalmente.",
    "assess.q4.o1": "Alto - me siento activo",
    "assess.q4.o2": "Medio - pasándola",
    "assess.q4.o3": "Bajo - me siento agotado",
    "assess.q5": "¿Qué sientes que necesitas más ahora?",
    "assess.q5.sub": "No hay respuesta incorrecta.",
    "assess.q5.o1": "Hablarlo",
    "assess.q5.o2": "Calmarme",
    "assess.q5.o3": "Dormir mejor",
    "assess.q5.o4": "Solo explorar",
    "assess.btnNext": "Continuar",
    "assess.btnResults": "Ver mis resultados",
    "assess.res.v1.title": "Parece que te va bien hoy",
    "assess.res.v1.desc": "¡Eso es maravilloso! Incluso en los días buenos, es hermoso tomarse un momento para registrarse.",
    "assess.res.v2.title": "Pareces un poco estresado hoy",
    "assess.res.v2.desc": "Está bien - la vida se vuelve pesada a veces. Unos momentos de atención plena pueden ayudar.",
    "assess.res.v3.title": "Parece que estás luchando un poco",
    "assess.res.v3.desc": "No estás solo en esto. Ya sea descanso o alguien con quien hablar, HOPEr está aquí.",
    "assess.res.v4.title": "Pareces abrumado en este momento",
    "assess.res.v4.desc": "Se necesita valor para registrarse con uno mismo. Por favor, sabe que eres visto y valorado.",
    "assess.msg.v1": "¡Veo que te va bien hoy! Estoy aquí si quieres hablar.",
    "assess.msg.v2": "Entiendo que has estado un poco ansioso. Vamos despacio - estoy aquí para escuchar.",
    "assess.msg.v3": "Veo que dormir ha sido difícil. Eso puede afectarlo todo.",
    "assess.msg.v4": "Veo que necesitas un poco de calma. Estoy aquí contigo.",
    "assess.msg.v5": "Veo que las cosas se sienten pesadas. No tienes que enfrentar esto solo.",
    "assess.res.btnSleep": "Modo Bienestar del Sueño",
    "assess.res.btnMindfulness": "Modo Mindfulness",
    "assess.res.btnChat": "Hablar con HOPEr",
    "score.mood": "Ánimo",
    "score.sleep": "Sueño",
    "score.calm": "Calma",
    "score.energy": "Energía",
    // Mindfulness
    "mind.title": "Mindfulness y Conexión",
    "mind.subtitle": "Elige una práctica para centrarte. Sin presiones, sin prisas.",
    "mind.m1.title": "Ejercicio de respiración",
    "mind.m1.desc": "Calma tu sistema nervioso con respiración guiada.",
    "mind.m1.s1": "Inhala lentamente por la nariz",
    "mind.m1.s2": "Mantén la respiración",
    "mind.m1.s3": "Exhala lentamente por la boca",
    "mind.m2.title": "Conexión (5-4-3-2-1)",
    "mind.m2.desc": "Conecta con tus sentidos para reducir la ansiedad.",
    "mind.m2.s1": "5 cosas que puedes ver",
    "mind.m2.s2": "4 cosas que puedes tocar",
    "mind.m2.s3": "3 cosas que puedes oír",
    "mind.m2.s4": "2 cosas que puedes oler",
    "mind.m2.s5": "1 cosa que puedes probar",
    "mind.m3.title": "Reflexión guiada",
    "mind.m3.desc": "Breves indicaciones para procesar pensamientos.",
    "mind.m3.s1": "¿De qué estás agradecido hoy?",
    "mind.m3.s2": "¿Cuál fue un pequeño logro reciente?",
    "mind.m3.s3": "¿Qué te gustaría soltar?",
    "mind.end": "Finalizar sesión",
    "mind.breathingLoop": "Inhala... Mantén... Exhala...",
    "mind.btnFinish": "Terminar sesión",
    "mind.btnNext": "Siguiente paso",
    "mind.btnAssess": "Haz una evaluación rápida primero",
    // Sleep
    "sleep.title": "Preparación para el sueño",
    "sleep.btnSkip": "Saltar al final",
    "sleep.dayGreeting": "Buenas tardes",
    "sleep.nightGreeting": "Buenas noches",
    "sleep.dayDesc": "Nunca es demasiado pronto para planificar un mejor descanso nocturno.",
    "sleep.nightDesc": "Preparemos tu mente y cuerpo para un sueño reparador.",
    "sleep.dim.title": "Reducir el brillo de la pantalla",
    "sleep.dim.desc": "Atenúa tu pantalla para reducir la exposición a la luz azul.",
    "sleep.dim.i1": "Activar Night Shift / Filtro de luz azul",
    "sleep.dim.i2": "Bajar el brillo de la pantalla por debajo del 50%",
    "sleep.dim.i3": "Considera usar una aplicación como f.lux",
    "sleep.breath.title": "Calentamiento respiratorio",
    "sleep.breath.desc": "Un ejercicio rápido de 4-7-8 para calmar tu sistema nervioso.",
    "sleep.breath.note": "Repite 4 ciclos, respirando suavemente por la nariz.",
    "sleep.script.title": "Historia relajante para dormir",
    "sleep.script.desc": "Escucha un breve guión de relajación guiada.",
    "sleep.script.content": "Imagínate acostado en un prado cómodo. El cielo es de un azul profundo y aterciopelado, salpicado de estrellas. Sientes la hierba suave debajo de ti y una brisa suave acaricia tu piel. Con cada respiración, dejas ir las preocupaciones del día, sumergiéndote más profundamente en la relajación...",
    "sleep.script.note": "Continúa leyendo a tu propio ritmo, o cierra los ojos y visualiza.",
    "sleep.check.title": "Lista de higiene del sueño",
    "sleep.check.desc": "Consejos personalizados basados en tu evaluación.",
    "sleep.check.i1": "Evitar noticias/redes sociales 1 hora antes de dormir",
    "sleep.check.i2": "Beber una taza de té de hierbas (manzanilla, lavanda)",
    "sleep.check.i3": "Ajustar la temperatura de la habitación a 18–20°C",
    "sleep.check.i4": "Usar cortinas opacas o una máscara para dormir",
    "sleep.check.i5": "Tener una libreta junto a la cama para los pensamientos",
    "sleep.check.note": "Marca los elementos a medida que los completes esta noche.",
    "sleep.close.title": "Todo listo",
    "sleep.close.desc": "Buen trabajo preparándote para dormir. ¡Dulces sueños!",
    "sleep.close.hero": "¡Has completado tu rutina relajante!",
    "sleep.close.sub": "Duerme bien y recuerda: HOPEr está aquí si necesitas apoyo.",
    "sleep.hygiene.title": "Consejos de higiene del sueño",
    "sleep.hygiene.desc": "Hábitos diarios para dormir mejor",
    "sleep.hygiene.i1": "Evitar la cafeína después de las 2 PM",
    "sleep.hygiene.i2": "Mantener tu dormitorio fresco y oscuro",
    "sleep.hygiene.i3": "Mantener un horario de sueño constante",
    "sleep.winddown.title": "Rutina relajante",
    "sleep.winddown.desc": "Ideas de relajación para la noche",
    "sleep.winddown.i1": "Leer un libro (sin pantallas)",
    "sleep.winddown.i2": "Estiramientos suaves o yoga",
    "sleep.winddown.i3": "Escribir las tareas de mañana",
    "sleep.btnNext": "Continuar",
    "sleep.btnPrevious": "Anterior",
    "sleep.btnFinish": "Terminar",
    "sleep.btnMindfulnessMode": "Prueba una meditación guiada en su lugar",
    "sleep.btnAskHoper": "Preguntar a HOPEr sobre el sueño",
    "sleep.btnAssess": "Hacer evaluación del sueño",
    "sleep.btnChat": "Chatear con HOPEr",
    "sleep.chatQuery": "Acabo de terminar mi rutina de sueño. ¿Podemos hablar de dormir?",
    "sleep.footer": "¿Necesitas más ayuda con el sueño?",
    // Hero
    "hero.title": "Tu viaje hacia la paz interior ",
    "hero.titleHighlight": "comienza con HOPEr",
    "hero.subtitle": "HOPEr es tu compañero de salud mental impulsado por IA, que ofrece un espacio seguro para la reflexión y el crecimiento.",
    "hero.btnSupport": "Soporte de crisis 24/7",
    "hero.btnLearnMore": "Saber más",
    "hero.btnFeeling": "¿Cómo te sientes?",
    "hero.chatPlaceholder": "Pregúntame lo que quieras...",
    "hero.typewriter1": "¿Cómo te sientes hoy?",
    "hero.typewriter2": "Estoy aquí para escucharte...",
    "hero.typewriter3": "¿Qué tienes en mente?",
    // Features
    "features.title": "Explora tu bienestar",
    "features.subtitle": "Descubre herramientas personalizadas para ayudarte a recuperar la paz interior.",
    "features.assessmentDesc": "Haz una evaluación de salud mental personalizada.",
    "features.mindfulnessDesc": "Explora respiración guiada, ejercicios de conexión y meditación.",
    "features.sleepDesc": "Prepárate para una noche reparadora con herramientas de relajación.",
    // Common
    "common.home": "Inicio",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.backHome": "Volver al inicio",
    "common.step": "Paso",
    "common.of": "de",
    "common.more": "... y más",
    "common.finish": "Terminar",
    "common.skip": "Saltar",
    "assessment.title": "¿Cómo te sientes ahora?",
    "mindfulness.title": "Atención plena y conexión a tierra",
    "mindfulness.subtitle":
      "Elige una práctica para centrarte. Sin presión, sin prisa.",
    "sleep.title": "Bienestar del sueño",
    "sleep.subtitle": "Relájate para una noche reparadora.",
    "sleep.dayGreeting": "¿Planeando dormir mejor esta noche?",
    "sleep.nightGreeting": "¿Listo para relajarte?",
    "sleep.dayDesc": "Preparémonos para una noche de descanso con algunos hábitos saludables.",
    "sleep.nightDesc": "Tómate un momento para relajarte y pasar al modo de sueño.",
    "sleep.btnFinish": "Finalizar",
    "sleep.btnNext": "Siguiente paso",
    "sleep.btnPrevious": "Anterior",
    "sleep.btnSkip": "Omitir",
    "chat.placeholder": "Escribe tu mensaje aquí...",
    "chat.send": "Enviar",
    "hero.title": "Transformar los momentos de estrés en pasos de esperanza ",
    "hero.titleHighlight": "Importa",
    "hero.subtitle": "Un compañero de IA seguro y empático que brinda apoyo de salud mental 24/7 para los estudiantes a través de orientación clínicamente verificada y conversaciones compasivas.",
    "hero.btnSupport": "Obtener Apoyo Ahora",
    "hero.btnLearnMore": "Más Información",
    "hero.btnFeeling": "¿Cómo te sientes?",
    "hero.chatPlaceholder": "ej. Me siento abrumado por los exámenes...",
    "hero.typewriter1": "¿Qué tienes en mente?",
    "hero.typewriter2": "¿Cómo te sientes hoy?",
    "hero.typewriter3": "¿Hay algo que te gustaría compartir?",
  },
  fr: {
    "nav.about": "À propos",
    "nav.howItWorks": "Comment ça marche",
    "nav.checkIn": "Enregistrement",
    "nav.mindfulness": "Pleine conscience",
    "nav.sleep": "Sommeil",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.chat": "Discuter avec HOPEr",
    "nav.getStarted": "Commencer",
    "nav.switchLanguage": "Changer de langue",
    "nav.explore": "Explorer",
    // Footer
    "footer.desc": "Soutenir la sensibilisation à la santé mentale et fournir des ressources à ceux qui en ont besoin.",
    "footer.quickLinks": "Liens Rapides",
    "footer.resources": "Ressources",
    "footer.crisis": "Ligne de Crise",
    "footer.support": "Groupes de Soutien",
    "footer.blog": "Blog",
    // Features
    "features.title": "Explorez votre bien-être",
    "features.subtitle": "Découvrez des outils personnalisés conçus pour vous aider à retrouver la paix intérieure et à gérer le stress efficacement.",
    "features.assessmentDesc": "Faites une évaluation personnalisée de votre santé mentale pour comprendre vos émotions.",
    "features.mindfulnessDesc": "Explorez la respiration guidée, les exercices d'ancrage et la méditation.",
    "features.sleepDesc": "Préparez-vous pour une nuit reposante avec des outils de relaxation et de suivi de sommeil.",
    // Meet Hoper
    "meet.titlePrefix": "Rencontrez",
    "meet.subtitle": "Un compagnon IA sûr et empathique",
    "meet.desc": "HOPEr comble l'écart entre les besoins de santé mentale des étudiants et le soutien disponible, en fournissant des conseils immédiats.",
    "meet.videoDesc": "Comprendre les difficultés que rencontrent les étudiants et pourquoi nous avons construit un compagnon IA.",
    "meet.f1.title": "Sûr et vérifié",
    "meet.f1.desc": "Construit sur des ressources vérifiées cliniquement et la sagesse spirituelle avec des filtres de sécurité appropriés.",
    "meet.f2.title": "Soutien empathique",
    "meet.f2.desc": "Fournit des conversations compatissantes et sans jugement conçues pour réduire le stress.",
    "meet.f3.title": "Disponibilité 24/7",
    "meet.f3.desc": "Toujours là quand vous avez besoin de soutien.",
    "meet.f4.title": "Basé sur les connaissances",
    "meet.f4.desc": "Toutes les réponses proviennent de textes de santé mentale et spirituels.",
    "meet.f5.title": "Références professionnelles",
    "meet.f5.desc": "Reconnaît lorsqu'une aide professionnelle est nécessaire et guide les utilisateurs.",
    "meet.f6.title": "Informations par l'IA",
    "meet.f6.desc": "Utilise l'IA avancée pour fournir des conseils personnalisés.",
    // Objectives
    "obj.titlePrefix": "Nos Principaux",
    "obj.titleSuffix": "Objectifs",
    "obj.o1.title": "Fournir des conseils empathiques",
    "obj.o1.desc": "Réduire le stress, motiver les étudiants et favoriser la résilience.",
    "obj.o2.title": "Minimiser les hallucinations",
    "obj.o2.desc": "Basé sur des connaissances vérifiées pour garantir des interactions responsables.",
    "obj.o3.title": "Développer un compagnon IA sûr",
    "obj.o3.desc": "Utilisation de la technologie RAG pour des réponses précises.",
    "obj.o4.title": "Construire une plateforme évolutive",
    "obj.o4.desc": "Conçu pour les écoles, les universités et les communautés.",
    "obj.o5.title": "Encourager des habitudes saines",
    "obj.o5.desc": "Promouvoir le bien-être tout en évitant une dépendance excessive à l'IA.",
    "obj.o6.title": "Garantir la confidentialité",
    "obj.o6.desc": "Protéger les données des utilisateurs et maintenir la confidentialité.",
    "obj.cta": "Découvrez HOPEr aujourd'hui",
    // How It Works
    "hiw.titlePrefix": "Comment",
    "hiw.titleSuffix": "Fonctionne",
    "hiw.desc": "Notre méthodologie combine une technologie d'IA de pointe avec des ressources vérifiées.",
    "hiw.s1.title": "Base de connaissances vérifiée",
    "hiw.s1.d1": "Ressources de santé mentale cliniquement vérifiées.",
    "hiw.s1.d2": "Organisé à partir de recherches révisées.",
    "hiw.s2.title": "Recherche sémantique",
    "hiw.s2.d1": "La base de données vectorielle Pinecone permet une récupération précise.",
    "hiw.s2.d2": "La recherche sémantique avancée garantit un contenu pertinent.",
    "hiw.s3.title": "Traitement de l'IA",
    "hiw.s3.d1": "L'architecture IA avancée synthétise les informations vérifiées.",
    "hiw.s3.d2": "Combine la précision de récupération avec l'empathie.",
    "hiw.s4.title": "Mesures de sécurité",
    "hiw.s4.d1": "Plusieurs couches de filtres de sécurité.",
    "hiw.s4.d2": "Détection de crise intégrée.",
    // AI Pipeline
    "pipe.titlePrefix": "Pipeline",
    "pipe.titleSuffix": "IA avancée",
    "pipe.f1.title": "Génération augmentée de récupération (RAG)",
    "pipe.f1.desc": "Combine la récupération d'informations en temps réel avec l'IA.",
    "pipe.f2.title": "Technologie de base de données vectorielle",
    "pipe.f2.desc": "Pinecone permet la compréhension sémantique.",
    "pipe.f3.title": "Architecture de sécurité",
    "pipe.f3.desc": "Plusieurs couches de sécurité assurent la protection des utilisateurs.",
    // CTA
    "cta.title": "Prêt à faire le premier pas ?",
    "cta.desc": "Rejoignez des milliers d'autres qui ont trouvé de l'espoir et du soutien dans notre communauté.",
    "cta.btn": "Commencez aujourd'hui",
    "cta.dialDesc": "Choisissez comment vous souhaitez nous contacter",
    "cta.email": "Envoyez un e-mail",
    "cta.call": "Appelez-nous",
    "cta.visit": "Visitez-nous",
    // Mood Check
    "mood.badge": "Nouvel outil",
    "mood.title": "Connaissez votre humeur en quelques minutes",
    "mood.desc": "Répondez à quelques questions et obtenez un aperçu de votre humeur avec des conseils de soutien.",
    "mood.features": "Prend moins de 3 minutes · Sûr · Sans jugement",
    "mood.btnStart": "Commencer le quiz",
    "mood.btnLearn": "En savoir plus",
    "mood.disclaimer": "Les scores sont des indicateurs. Si vous ne vous sentez pas en sécurité, demandez de l'aide.",
    // Assessment
    "assess.title": "HOPEr Check-In",
    "assess.prev": "Précédent",
    "assess.q1": "Comment décririez-vous votre humeur en ce moment ?",
    "assess.q1.sub": "Choisissez l'emoji qui se rapproche le plus de ce que vous ressentez.",
    "assess.q1.o1": "Très bas",
    "assess.q1.o2": "Bas",
    "assess.q1.o3": "Bien",
    "assess.q1.o4": "Bon",
    "assess.q1.o5": "Génial",
    "assess.q2": "Comment se passe votre sommeil ces derniers temps ?",
    "assess.q2.sub": "Pensez aux 2-3 dernières nuits.",
    "assess.q2.o1": "Bien - Je suis bien reposé",
    "assess.q2.o2": "Correct - peut mieux faire",
    "assess.q2.o3": "Mauvais - troubles du sommeil",
    "assess.q3": "Vous sentez-vous anxieux ou réfléchissez-vous trop ?",
    "assess.q3.sub": "Soyez honnête - c'est juste pour vous.",
    "assess.q3.o1": "Pas du tout",
    "assess.q3.o2": "Un petit peu",
    "assess.q3.o3": "Oui, pas mal",
    "assess.q4": "Quel est votre niveau d'énergie en ce moment ?",
    "assess.q4.sub": "Physiquement et mentalement.",
    "assess.q4.o1": "Élevé - je me sens actif",
    "assess.q4.o2": "Moyen - ça va",
    "assess.q4.o3": "Bas - je me sens épuisé",
    "assess.q5": "De quoi avez-vous le plus besoin en ce moment ?",
    "assess.q5.sub": "Il n'y a pas de mauvaise réponse.",
    "assess.q5.o1": "En parler",
    "assess.q5.o2": "Se calmer",
    "assess.q5.o3": "Mieux dormir",
    "assess.q5.o4": "Juste explorer",
    "assess.btnNext": "Continuer",
    "assess.btnResults": "Voir mes résultats",
    "assess.res.v1.title": "Vous semblez aller bien aujourd'hui",
    "assess.res.v1.desc": "C'est merveilleux ! Même les bons jours, c'est beau de prendre un moment pour se retrouver.",
    "assess.res.v2.title": "Vous semblez un peu stressé aujourd'hui",
    "assess.res.v2.desc": "C'est normal - la vie est parfois lourde. Quelques moments de pleine conscience peuvent aider.",
    "assess.res.v3.title": "Vous semblez lutter un peu",
    "assess.res.v3.desc": "Vous n'êtes pas seul. Que ce soit du repos ou quelqu'un à qui parler, HOPEr est là.",
    "assess.res.v4.title": "Vous semblez dépassé en ce moment",
    "assess.res.v4.desc": "Il faut du courage pour faire le point avec soi-même. Sachez que vous êtes vu et valorisé.",
    "assess.msg.v1": "Je vois que vous allez bien aujourd'hui ! Je suis là si vous voulez parler.",
    "assess.msg.v2": "Je comprends que vous soyez un peu anxieux. Allons-y doucement - je suis là pour vous écouter.",
    "assess.msg.v3": "Je vois que le sommeil a été difficile. Cela peut tout affecter.",
    "assess.msg.v4": "Je vois que vous avez besoin de calme. Je suis là avec vous.",
    "assess.msg.v5": "Je vois que les choses sont lourdes. Vous n'avez pas à affronter cela seul.",
    "assess.res.btnSleep": "Mode Bien-être du Sommeil",
    "assess.res.btnMindfulness": "Mode Pleine Conscience",
    "assess.res.btnChat": "Parler à HOPEr",
    "score.mood": "Humeur",
    "score.sleep": "Sommeil",
    "score.calm": "Calme",
    "score.energy": "Énergie",
    // Mindfulness
    "mind.title": "Pleine conscience",
    "mind.subtitle": "Choisissez une pratique pour vous centrer. Pas de pression.",
    "mind.m1.title": "Exercice de respiration",
    "mind.m1.desc": "Calmez votre système nerveux.",
    "mind.m1.s1": "Inspirez lentement par le nez",
    "mind.m1.s2": "Retenez votre respiration",
    "mind.m1.s3": "Expirez lentement par la bouche",
    "mind.m2.title": "Ancrage (5-4-3-2-1)",
    "mind.m2.desc": "Connectez-vous à vos sens.",
    "mind.m2.s1": "5 choses que vous pouvez voir",
    "mind.m2.s2": "4 choses que vous pouvez toucher",
    "mind.m2.s3": "3 choses que vous pouvez entendre",
    "mind.m2.s4": "2 choses que vous pouvez sentir",
    "mind.m2.s5": "1 chose que vous pouvez goûter",
    "mind.m3.title": "Réflexion guidée",
    "mind.m3.desc": "Brefs messages pour traiter vos pensées.",
    "mind.m3.s1": "Une chose pour laquelle vous êtes reconnaissant ?",
    "mind.m3.s2": "Une petite victoire récente ?",
    "mind.m3.s3": "Que voulez-vous laisser partir ?",
    "mind.end": "Terminer la session",
    "mind.breathingLoop": "Inspirez... Retenez... Expirez...",
    "mind.btnFinish": "Terminer",
    "mind.btnNext": "Suivant",
    "mind.btnAssess": "Faites d'abord une évaluation",
    // Common
    "common.home": "Accueil",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.backHome": "Retour à l'accueil",
    "common.step": "Étape",
    "common.of": "sur",
    "common.more": "... et plus",
    "common.finish": "Terminer",
    "common.skip": "Sauter",
    "assessment.title": "Comment vous sentez-vous maintenant ?",
    "mindfulness.title": "Pleine conscience et ancrage",
    "mindfulness.subtitle":
      "Choisissez une pratique pour vous recentrer. Pas de pression, pas de précipitation.",
    "sleep.title": "Bien-être du sommeil",
    "sleep.subtitle": "Détendez-vous pour une nuit reposante.",
    "sleep.dayGreeting": "Vous prévoyez de mieux dormir ce soir ?",
    "sleep.nightGreeting": "Prêt à vous détendre ?",
    "sleep.dayDesc": "Préparons-nous pour une nuit reposante avec de saines habitudes.",
    "sleep.nightDesc": "Prenez un moment pour vous détendre et passer en mode sommeil.",
    "sleep.btnFinish": "Terminer",
    "sleep.btnNext": "Étape suivante",
    "sleep.btnPrevious": "Précédent",
    "sleep.btnSkip": "Passer",
    "chat.placeholder": "Tapez votre message ici...",
    "chat.send": "Envoyer",
    "hero.title": "Transformer les moments de stress en étapes d'espoir ",
    "hero.titleHighlight": "Compte",
    "hero.subtitle": "Un compagnon IA sûr et empathique offrant un soutien en santé mentale 24h/24 et 7j/7 aux étudiants via des conseils cliniquement vérifiés et des conversations compatissantes.",
    "hero.btnSupport": "Obtenir de l'aide",
    "hero.btnLearnMore": "En savoir plus",
    "hero.btnFeeling": "Comment vous sentez-vous ?",
    "hero.chatPlaceholder": "ex. Je me sens dépassé par les examens...",
    "hero.typewriter1": "À quoi pensez-vous ?",
    "hero.typewriter2": "Comment vous sentez-vous aujourd'hui ?",
    "hero.typewriter3": "Y a-t-il quelque chose que vous aimeriez partager ?",
  },
  ar: {
    "nav.about": "معلومات عنا",
    "nav.howItWorks": "كيف يعمل",
    "nav.checkIn": "تسجيل الوصول",
    "nav.mindfulness": "اليقظة",
    "nav.sleep": "النوم",
    "nav.faq": "الأسئلة الشائعة",
    "nav.contact": "اتصل بنا",
    "nav.chat": "تحدث مع HOPEr",
    "nav.getStarted": "البدء",
    "nav.switchLanguage": "تغيير اللغة",
    "nav.explore": "استكشف",
    // Footer
    "footer.desc": "دعم الوعي بالصحة العقلية وتوفير الموارد للمحتاجين.",
    "footer.quickLinks": "روابط سريعة",
    "footer.resources": "الموارد",
    "footer.crisis": "خط الأزمات",
    "footer.support": "مجموعات الدعم",
    "footer.blog": "المدونة",
    // Features
    "features.title": "استكشف صحتك",
    "features.subtitle": "اكتشف أدوات مخصصة مصممة لمساعدتك على استعادة السلام الداخلي وإدارة التوتر بفعالية.",
    "features.assessmentDesc": "قم بإجراء تقييم شخصي للصحة العقلية لفهم مشاعرك.",
    "features.mindfulnessDesc": "استكشف التنفس الموجه وتمارين التأريض والتأمل.",
    "features.sleepDesc": "استعد لليلة مريحة مع أدوات الاسترخاء وتتبع النوم.",
    // Meet Hoper
    "meet.titlePrefix": "تعرف على",
    "meet.subtitle": "رفيق ذكاء اصطناعي آمن وعاطفي",
    "meet.desc": "HOPEr يسد الفجوة بين احتياجات الصحة العقلية للطلاب والدعم المتاح، مما يوفر إرشادات فورية وآمنة.",
    "meet.videoDesc": "فهم التحديات التي يواجهها الطلاب ولماذا قمنا ببناء رفيق ذكاء اصطناعي يهتم حقًا",
    "meet.f1.title": "آمن ومتحقق منه",
    "meet.f1.desc": "مبني على موارد الصحة العقلية الموثوقة سريريًا والحكمة الروحية.",
    "meet.f2.title": "دعم عاطفي",
    "meet.f2.desc": "يوفر محادثات متعاطفة وغير قضائية مصممة لتقليل التوتر وبناء المرونة.",
    "meet.f3.title": "متاح 24/7",
    "meet.f3.desc": "دائمًا هناك عندما تحتاج إلى دعم، مما يوفر راحة فورية من التوتر.",
    "meet.f4.title": "مبني على المعرفة",
    "meet.f4.desc": "جميع الاستجابات مستمدة من نصوص الصحة العقلية المنسقة، مما يضمن الدقة.",
    "meet.f5.title": "الإحالات المهنية",
    "meet.f5.desc": "يتعرف على متى تكون المساعدة المهنية ضرورية ويوجه المستخدمين إلى الموارد المناسبة.",
    "meet.f6.title": "رؤى مدعومة بالذكاء الاصطناعي",
    "meet.f6.desc": "يستخدم الذكاء الاصطناعي المتقدم لتوفير إرشادات مخصصة تناسب احتياجاتك وظروفك الفريدة.",
    // Objectives
    "obj.titlePrefix": "أهدافنا",
    "obj.titleSuffix": "الأساسية",
    "obj.o1.title": "توفير توجيه متعاطف",
    "obj.o1.desc": "تقليل التوتر وتحفيز الطلاب وتعزيز المرونة.",
    "obj.o2.title": "تقليل الهلوسة",
    "obj.o2.desc": "مبني على المعرفة التي تم التحقق منها لضمان تفاعلات مسؤولة.",
    "obj.o3.title": "تطوير رفيق ذكاء اصطناعي آمن",
    "obj.o3.desc": "استخدام تقنية RAG لاستجابات دقيقة وموثوقة.",
    "obj.o4.title": "بناء منصة قابلة للتطوير",
    "obj.o4.desc": "مصممة للمدارس والجامعات والمجتمعات.",
    "obj.o5.title": "تشجيع العادات الصحية",
    "obj.o5.desc": "تعزيز الرفاهية مع منع الاعتماد المفرط على الذكاء الاصطناعي.",
    "obj.o6.title": "ضمان الخصوصية",
    "obj.o6.desc": "حماية بيانات المستخدم والحفاظ على السرية.",
    "obj.cta": "جرب HOPEr اليوم",
    // How It Works
    "hiw.titlePrefix": "كيف",
    "hiw.titleSuffix": "يعمل",
    "hiw.desc": "تجمع منهجيتنا بين تكنولوجيا الذكاء الاصطناعي المتطورة والموارد التي تم التحقق منها عياديًا.",
    "hiw.s1.title": "قاعدة معرفة تم التحقق منها",
    "hiw.s1.d1": "موارد الصحة العقلية السريرية.",
    "hiw.s1.d2": "منسقة من الأبحاث التي راجعها النظراء.",
    "hiw.s2.title": "الاسترجاع الدلالي",
    "hiw.s2.d1": "تتيح قاعدة بيانات المتجهات استرجاعًا دقيقًا.",
    "hiw.s2.d2": "يضمن البحث الدلالي المتقدم المحتوى الأكثر صلة.",
    "hiw.s3.title": "معالجة الذكاء الاصطناعي",
    "hiw.s3.d1": "تجمع بنية الذكاء الاصطناعي المتقدمة بين المعلومات التي تم التحقق منها في استجابات متعاطفة.",
    "hiw.s3.d2": "يجمع بين دقة الاسترجاع والتعاطف التوليدي.",
    "hiw.s4.title": "تدابير السلامة",
    "hiw.s4.d1": "طبقات متعددة من مرشحات الأمان.",
    "hiw.s4.d2": "اكتشاف الأزمات المدمج.",
    // AI Pipeline
    "pipe.titlePrefix": "خط أنابيب",
    "pipe.titleSuffix": "الذكاء الاصطناعي المتقدم",
    "pipe.f1.title": "توليد المعزز بالاسترجاع (RAG)",
    "pipe.f1.desc": "يجمع بين استرجاع المعلومات والذكاء الاصطناعي التوليدي لاستجابات دقيقة.",
    "pipe.f2.title": "تكنولوجيا قاعدة البيانات المتجهة",
    "pipe.f2.desc": "يُمكن الاستيعاب الدلالي والاسترجاع الدقيق.",
    "pipe.f3.title": "هيكل أمان قوي",
    "pipe.f3.desc": "تدابير سلامة متعددة تضمن حماية المستخدم.",
    // CTA
    "cta.title": "هل أنت مستعد لاتخاذ الخطوة الأولى؟",
    "cta.desc": "انضم إلى الآلاف الآخرين الذين وجدوا الأمل والدعم من خلال مجتمعنا.",
    "cta.btn": "ابدأ اليوم",
    "cta.dialDesc": "اختر كيف ترغب في التواصل معنا",
    "cta.email": "راسلنا",
    "cta.call": "اتصل بنا",
    "cta.visit": "زورنا",
    // Mood Check
    "mood.badge": "أداة رفاهية جديدة",
    "mood.title": "اكتشف مزاجك في دقائق",
    "mood.desc": "أجب بصدق على ثمانية أسئلة واحصل على لقطة مزاجية ودية مع نصائح داعمة.",
    "mood.features": "يستغرق أقل من 3 دقائق · آمن · بدون أحكام",
    "mood.btnStart": "ابدأ الاختبار",
    "mood.btnLearn": "اعرف المزيد",
    "mood.disclaimer": "الدرجات هي مؤشرات ، وليست تشخيصات طبية. إذا تفاقم الأمر، اطلب المساعدة.",
    // Assessment
    "assess.title": "تسجيل دخول HOPEr",
    "assess.prev": "السابق",
    "assess.q1": "كيف تصف مزاجك الآن؟",
    "assess.q1.sub": "اختر الرموز التعبيرية الأقرب لما تشعر به.",
    "assess.q1.o1": "منخفض جدا",
    "assess.q1.o2": "منخفض",
    "assess.q1.o3": "حسنا",
    "assess.q1.o4": "جيد",
    "assess.q1.o5": "رائع",
    "assess.q2": "كيف كان نومك مؤخرا؟",
    "assess.q2.sub": "فكر في آخر ليلتين أو ثلاث ليالٍ.",
    "assess.q2.o1": "جيد - لقد ارتحت جيدًا",
    "assess.q2.o2": "حسنا - يمكن أن يكون أفضل",
    "assess.q2.o3": "سيء - مشكلة في النوم",
    "assess.q3": "هل تشعر بالقلق أو التفكير الزائد؟",
    "assess.q3.sub": "كن صادقًا - هذا لك فقط.",
    "assess.q3.o1": "على الاطلاق",
    "assess.q3.o2": "قليلا",
    "assess.q3.o3": "نعم ، الكثير جدا",
    "assess.q4": "كيف هو مستوى طاقتك الآن؟",
    "assess.q4.sub": "جسديا وعقليا.",
    "assess.q4.o1": "عالي - أشعر بالنشاط",
    "assess.q4.o2": "متوسط - يسير",
    "assess.q4.o3": "منخفض - أشعر بالاستنزاف",
    "assess.q5": "ما الذي تشعر أنك بحاجة إليه الآن؟",
    "assess.q5.sub": "لا توجد إجابة خاطئة.",
    "assess.q5.o1": "تحدث عنها",
    "assess.q5.o2": "اهدأ",
    "assess.q5.o3": "نوم أفضل",
    "assess.q5.o4": "فقط استكشف",
    "assess.btnNext": "استمر",
    "assess.btnResults": "انظر نتائجي",
    "assess.res.v1.title": "تبدو في حالة جيدة اليوم",
    "assess.res.v1.desc": "هذا رائع! حتى في الأيام الخوالي ، من الجميل أن تتوقف لحظة وتتحقق من نفسك.",
    "assess.res.v2.title": "تبدو متوتراً قليلاً اليوم",
    "assess.res.v2.desc": "لا بأس - تصبح الحياة ثقيلة أحيانًا. بعض لحظات اليقظة يمكن أن تساعد.",
    "assess.res.v3.title": "تبدو وكأنك تعاني قليلاً",
    "assess.res.v3.desc": "أنت لست وحدك في هذا. سواء كان ذلك راحة أو شخصًا تتحدث إليه ، فإن HOPEr هنا.",
    "assess.res.v4.title": "تبدو مرهقًا الآن",
    "assess.res.v4.desc": "يتطلب الأمر شجاعة للتحقق من نفسك. يرجى العلم أنك مرئي ومقدر.",
    "assess.msg.v1": "أرى أنك تقوم بعمل جيد اليوم! أنا هنا إذا كنت تريد التحدث.",
    "assess.msg.v2": "أفهم أنك كنت قلقًا بعض الشيء. دعونا نأخذ الأمر ببطء - أنا هنا للاستماع.",
    "assess.msg.v3": "أرى أن النوم كان صعبًا. هذا يمكن أن يؤثر على كل شيء.",
    "assess.msg.v4": "أرى أنك بحاجة إلى بعض الهدوء. أنا هنا معك.",
    "assess.msg.v5": "أرى أن الأمور تبدو ثقيلة. ليس عليك مواجهة هذا وحدك.",
    "assess.res.btnSleep": "وضع عافية النوم",
    "assess.res.btnMindfulness": "وضع اليقظة",
    "assess.res.btnChat": "تحدث إلى HOPEr",
    "score.mood": "المزاج",
    "score.sleep": "النوم",
    "score.calm": "الهدوء",
    "score.energy": "الطاقة",
    // Mindfulness
    "mind.title": "اليقظة والتمريض الذهني",
    "mind.subtitle": "اختر ممارسة لتركيز نفسك. لا ضغوط ، لا استعجال.",
    "mind.m1.title": "تمرين التنفس",
    "mind.m1.desc": "هدئ جهازك العصبي بتمارين التنفس الموجهة.",
    "mind.m1.s1": "استنشق ببطء من خلال أنفك",
    "mind.m1.s2": "احبس أنفاسك",
    "mind.m1.s3": "ازفر ببطء من خلال فمك",
    "mind.m2.title": "التمريض الذهني (5-4-3-2-1)",
    "mind.m2.desc": "تواصل مع حواسك لتقليل القلق.",
    "mind.m2.s1": "5 أشياء يمكنك رؤيتها",
    "mind.m2.s2": "4 أشياء يمكنك لمسها",
    "mind.m3.title": "تأمل موجه",
    "mind.m3.desc": "مطالبات تدوين قصيرة لمعالجة الأفكار.",
    "mind.end": "إنهاء الجلسة",
    "mind.breathingLoop": "شهيق... حبس... زفير...",
    "mind.btnFinish": "إنهاء",
    "mind.btnNext": "الخطوة التالية",
    "mind.btnAssess": "قم بإجراء تقييم سريع أولاً",
    // Common
    "common.home": "الرئيسية",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.backHome": "العودة إلى الرئيسية",
    "common.step": "خطوة",
    "common.of": "من",
    "common.more": "... و اكثر",
    "common.finish": "إنهاء",
    "common.skip": "تخطي",
    "assessment.title": "كيف تشعر الآن؟",
    "mindfulness.title": "اليقظة والتأريض",
    "mindfulness.subtitle": "اختر ممارسة لتركيز نفسك. لا ضغط، لا عجلة.",
    "sleep.title": "صحة النوم",
    "sleep.subtitle": "استرخِ ليلة مريحة.",
    "sleep.dayGreeting": "تخطط لنوم أفضل الليلة؟",
    "sleep.nightGreeting": "هل أنت مستعد للاسترخاء؟",
    "sleep.dayDesc": "دعونا نستعد لليلة مريحة مع بعض العادات الصحية.",
    "sleep.nightDesc": "خذ لحظة للاسترخاء والانتقال إلى وضع النوم.",
    "sleep.btnFinish": "إنهاء",
    "sleep.btnNext": "الخطوة التالية",
    "sleep.btnPrevious": "السابق",
    "sleep.btnSkip": "تخطي",
    "chat.placeholder": "اكتب رسالتك هنا...",
    "chat.send": "إرسال",
    "hero.title": "تحويل لحظات التوتر إلى خطوات من الأمل ",
    "hero.titleHighlight": "أمر يهم",
    "hero.subtitle": "رفيق ذكاء اصطناعي آمن ومتعاطف يوفر دعمًا للصحة العقلية على مدار الساعة طوال أيام الأسبوع للطلاب من خلال إرشادات تم التحقق منها سريريًا ومحادثات رحيمة.",
    "hero.btnSupport": "احصل على الدعم الآن",
    "hero.btnLearnMore": "اعرف المزيد",
    "hero.btnFeeling": "كيف تشعر؟",
    "hero.chatPlaceholder": "مثلًا: أشعر بالإرهاق بسبب الامتحانات...",
    "hero.typewriter1": "بماذا تفكر؟",
    "hero.typewriter2": "كيف تشعر اليوم؟",
    "hero.typewriter3": "هل هناك شيء تود مشاركته؟",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("hoper_language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("hoper_language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
